/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.tokamak.xview;

import javafx.application.Application;
import javafx.scene.Scene;

public class Main extends Application {

    public static void main(String[] args) { 
    	launch(agrs);       
    }

    @Override
	public void start(Stage primaryStage) throws Exception {
		BorderPane root = new BorderPane();
		primaryStage.setTitle("xview");
		primaryStage.setScene(new Scene(root, 800, 600));
		primaryStage.show();
	}
}
